eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    metadata-map:
      management.port: ${management.port:8081}
server:
  port: 8030
  
info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  appConfig: login-server

management:
  port: 8990