server: 
  port: 8081
spring: 
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: local
      host: localhost
      port: 27017